"""Discover and install pip dependencies declared by directory plugins."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from ly_next.core.config import get_data_root, get_project_root

_SKIP_REQUIREMENT_NAMES = frozenset({"ly-next", "ly_next", "LY-NEXT"})


def _requirement_name(line: str) -> str:
    token = str(line or "").strip().split("#", 1)[0].strip()
    if not token:
        return ""
    token = token.split(";")[0].strip()
    for sep in ("==", ">=", "<=", "~=", "!=", "<", ">", "[", "@"):
        token = token.split(sep, 1)[0].strip()
    return token.replace("_", "-").lower()


def _should_skip_requirement(line: str) -> bool:
    name = _requirement_name(line)
    if not name:
        return True
    return name in {n.replace("_", "-").lower() for n in _SKIP_REQUIREMENT_NAMES}


def _parse_requirements_text(text: str) -> list[str]:
    out: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-r ") or line.startswith("--"):
            continue
        if _should_skip_requirement(line):
            continue
        out.append(line)
    return out


def _read_requirements_file(path: Path) -> list[str]:
    if not path.is_file():
        return []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    return _parse_requirements_text(text)


def _read_pyproject_dependencies(path: Path) -> list[str]:
    if not path.is_file():
        return []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return []
    if sys.version_info >= (3, 11):
        import tomllib

        try:
            data = tomllib.loads(text)
        except tomllib.TOMLDecodeError:
            return []
    else:
        return []
    project = data.get("project")
    if not isinstance(project, dict):
        return []
    deps = project.get("dependencies")
    if not isinstance(deps, list):
        return []
    return [str(item).strip() for item in deps if str(item).strip() and not _should_skip_requirement(str(item))]


def _plugin_scan_roots() -> list[Path]:
    from ly_next.core.plugin.loader import _plugin_dir, _plugin_extra_dirs

    roots: list[Path] = [_plugin_dir()]
    roots.extend(_plugin_extra_dirs())
    unique: list[Path] = []
    seen: set[str] = set()
    for root in roots:
        key = str(root.resolve())
        if key in seen:
            continue
        seen.add(key)
        unique.append(root)
    return unique


def discover_plugin_requirements() -> list[dict[str, Any]]:
    """Scan plugin directories for requirements.txt / pyproject.toml dependencies."""
    project_root = get_project_root()
    plugins: list[dict[str, Any]] = []
    global_seen: set[str] = set()

    for root in _plugin_scan_roots():
        if not root.is_dir():
            continue
        for child in sorted(root.iterdir()):
            if not child.is_dir() or child.name.startswith("."):
                continue
            reqs: list[str] = []
            for line in _read_requirements_file(child / "requirements.txt"):
                if line not in global_seen:
                    global_seen.add(line)
                    reqs.append(line)
            for line in _read_pyproject_dependencies(child / "pyproject.toml"):
                if line not in global_seen:
                    global_seen.add(line)
                    reqs.append(line)
            if not reqs:
                continue
            try:
                rel = str(child.resolve().relative_to(project_root.resolve())).replace("\\", "/")
            except ValueError:
                rel = str(child)
            plugins.append({"plugin_dir": rel, "requirements": reqs})

    return plugins


def plugin_requirements_manifest_path() -> Path:
    return get_data_root() / "plugin_requirements.txt"


def write_plugin_requirements_manifest(requirements: list[str]) -> Path:
    path = plugin_requirements_manifest_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# Generated by LY-NEXT plugin dependency sync.",
        "# Used by: uv run ly plugins sync-deps",
        "# Prefer project sync: uv run sync  (inexact uv sync + plugin deps)",
        "",
    ]
    path.write_text("\n".join(header + requirements) + ("\n" if requirements else ""), encoding="utf-8")
    return path


def sync_plugin_dependencies(*, install: bool = True) -> dict[str, Any]:
    """Collect plugin requirements and optionally install them into the project venv."""
    discovered = discover_plugin_requirements()
    requirements: list[str] = []
    for item in discovered:
        requirements.extend(item["requirements"])

    manifest = write_plugin_requirements_manifest(requirements)
    rel_manifest = str(manifest.relative_to(get_project_root())).replace("\\", "/")
    result: dict[str, Any] = {
        "ok": True,
        "plugins": discovered,
        "requirements": requirements,
        "manifest": rel_manifest,
        "installed": 0,
        "message": "",
    }

    if not requirements:
        result["message"] = "未发现需要安装的插件依赖。"
        return result

    if not install:
        result["message"] = f"已写入清单 {rel_manifest}（共 {len(requirements)} 项）。"
        return result

    if shutil.which("uv") is None:
        raise RuntimeError("未找到 uv 命令，无法安装插件依赖")

    proc = subprocess.run(
        ["uv", "pip", "install", "-r", str(manifest)],
        cwd=str(get_project_root()),
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        err = (proc.stderr or proc.stdout or "").strip()
        raise RuntimeError(err or f"uv pip install 失败 (exit {proc.returncode})")

    result["installed"] = len(requirements)
    result["message"] = f"已安装 {len(requirements)} 个插件依赖（清单：{rel_manifest}）。"
    result["stdout"] = (proc.stdout or "").strip() or None
    return result


def run_plugin_deps_sync_cli(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Install pip dependencies declared by plugins/local/")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only write data/ly_next/plugin_requirements.txt without installing",
    )
    args = parser.parse_args(argv)
    try:
        result = sync_plugin_dependencies(install=not args.dry_run)
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(result.get("message") or "done")
    for item in result.get("plugins") or []:
        reqs = ", ".join(item.get("requirements") or [])
        print(f"  - {item.get('plugin_dir')}: {reqs}")
    return 0
